version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft_server
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "votre_mot_de_passe_rcon_sécurisé"
      RCON_PORT: "25575"
    networks:
      - minecraft_network
    restart: on-failure
    volumes:
      - "./data:/minecraft"
    user: "1000:1000"
  flask_api:
    build: ./flask_api
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      RCON_HOST: "minecraft_server"
      RCON_PORT: "25575"
      RCON_PASSWORD: "votre_mot_de_passe_rcon_sécurisé"
      BASIC_AUTH_USERNAME: "mael"
      BASIC_AUTH_PASSWORD: "votre_mot_de_passe_flask"
      GAME_PASSWORD: "mot_de_passe_secret"
    depends_on:
      - minecraft
    volumes:
      - "./flask_api:/app"
    networks:
      - minecraft_network
    restart: on-failure

networks:
  minecraft_network:
    driver: bridge
