version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft_server
    ports:
      - "25565:25565"  # Port du serveur Minecraft pour les joueurs
      - "25575:25575"  # Port RCON du serveur Minecraft
    environment:
      TYPE: "SPIGOT"
      VERSION: "1.21.3"
      EULA: "TRUE"
      MAX_MEMORY: "16G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "votre_mot_de_passe_rcon_sécurisé"
      RCON_PORT: "25575"
      ONLINE_MODE: "FALSE" # For cracked servers
    networks:
      - minecraft_network
    restart: on-failure
    volumes:
      - "./data:/data"
      - "./plugins_source:/plugins_source"
    entrypoint: /bin/bash -c "/initialize_plugins.sh && /start"

  flask_api:
    build: ./flask_api
    container_name: flask_api
    ports:
      - "5000:5000"  # Expose le port 5000 du conteneur vers le port 5000 de l'hôte
    environment:
      RCON_HOST: "minecraft_server"  # Nom du conteneur Minecraft
      RCON_PORT: "25575"
      RCON_PASSWORD: "votre_mot_de_passe_rcon_sécurisé"
      BASIC_AUTH_USERNAME: "mael"
      BASIC_AUTH_PASSWORD: "votre_mot_de_passe_flask"
      GAME_PASSWORD: "mot_de_passe_secret"  # In game password to play
    depends_on:
      - minecraft
    volumes:
      - "./flask_api:/app"
    networks:
      - minecraft_network
    restart: on-failure

networks:
  minecraft_network:
    driver: bridge
